---
- name: Provisionar servidor de aplicação Docker na Oracle Cloud (Oracle Linux 9)
  hosts: oci_servers
  become: true
  vars:
    app_user: "mvrc"
    my_ssh_public_key_path: "~/.ssh/id_ed25519.pub"
    jenkins_ssh_public_key_path: "/var/lib/jenkins/.ssh/ansible_key.pub"
    mvrc_ssh_public_keys:
      - "{{ my_ssh_public_key_path }}"
      - "{{ jenkins_ssh_public_key_path }}"

  pre_tasks:
    - name: Aguardar SSH ficar disponível
      wait_for_connection:
        delay: 10
        timeout: 180

    - name: Atualizar cache de pacotes (dnf)
      dnf:
        update_cache: yes

  roles:
    - mvrc-user
    - swap
    - base
    - firewalld
    - docker
    - traefik
